apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels: 
    app: backend-feed
spec: 
  replicas: 3
  selector:
      matchLabels:
        app: backend-feed
 
  template:
    metadata:
      name: backend-feed
      labels: 
        app: backend-feed
    spec: 
      containers:
        - name:  udagram-api-feed
          image: ifecodev/udagram-api-feed:2
          # command: [ "/bin/sh", "-c", "env" ]
          envFrom:
            - secretRef:
                name: env-secret
          envFrom:
            - configMapRef:
                name: env-config
        
          ports:
          - containerPort: 8080