name: Build and Publish Udagram

on:
  # run it on push to the default repository branch
  push:
    branches: [main]
  # run it during pull request
  pull_request:

jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build image feed
        uses: docker/build-push-action@v3
        with:
          context: ./udagram-api-feed
          tags: ifecodev/udagram-api-feed:v1
          push: ${{ github.ref == 'refs/heads/main' }}
      - name: Build image fontend
        uses: docker/build-push-action@v3
        with:
          context: ./udagram-frontend
          tags: ifecodev/udagram-frontend:v1
          push: ${{ github.ref == 'refs/heads/main' }}
      - name: Build image user
        uses: docker/build-push-action@v3
        with:
          context: ./udagram-api-user
          tags: ifecodev/udagram-api-user:v1
          push: ${{ github.ref == 'refs/heads/main' }}
      - name: Build image reverse proxy
        uses: docker/build-push-action@v3
        with:
          context: ./udagram-reverseproxy
          tags: ifecodev/udagram-reverseproxy:v1
          push: ${{ github.ref == 'refs/heads/main' }}
